# Generated by Django 5.2.1 on 2025-05-27 04:31

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('Mob', models.BigIntegerField(unique=True)),
                ('Email', models.EmailField(max_length=254)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pond',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('latlong', models.CharField(max_length=150)),
                ('location', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326, unique=True)),
                ('area', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pH', models.FloatField()),
                ('dissolved_oxygen', models.FloatField()),
                ('NDVI', models.FloatField()),
                ('NDTI', models.FloatField()),
                ('GCI', models.FloatField()),
                ('NDCI', models.FloatField()),
                ('NDWI', models.FloatField()),
                ('TSS', models.FloatField()),
                ('CDOM', models.FloatField()),
                ('AQUATIC_MACROPYTES', models.FloatField()),
                ('Phycocyanin', models.FloatField()),
                ('Chl_a', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.pond')),
            ],
        ),
    ]
