# Generated by Django 5.2.1 on 2025-05-24 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_pond_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='pond',
            name='user',
            field=models.ForeignKey(default=1234567890, on_delete=django.db.models.deletion.CASCADE, to='app1.myuser'),
            preserve_default=False,
        ),
    ]
